# Use a base image with JDK
FROM anujachavan/openjdk-24-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the application JAR file
COPY target/hospital-management-frontend-0.0.1-SNAPSHOT.jar /app/hospital-console.jar

# Start the application
CMD ["java", "-jar","hospital-console.jar"]

