FROM anujachavan/directory-service

RUN apt update

RUN apt install -y iputils-ping

WORKDIR /app

COPY /target/directory-service-0.0.1-SNAPSHOT.jar /app/directory-service.jar

CMD ["java","-jar","/app/directory-service.jar"]

# docker run -d -it -e DB_HOST=172.20.0.2 -e DB_NAME=directory_service_db --name directory-service --network hospital-management-network org.dnyanyog/directory-service  

