FROM openjdk:24-jdk-slim
RUN apt update

RUN apt install -y iputils-ping

WORKDIR /app

COPY target/appointment-service-docker-image-0.0.1-SNAPSHOT.jar /app/appointment-service.jar

CMD ["java","-jar","/app/appointment-service.jar"]


# docker build -t appointment-service:latest -f dockerfile .
# docker run -it --rm --name appointment-service --network hospital-management  appointment-service:latest
# docker run --rm -it -e DB_HOST=172.20.0.2/16 -e DB_NAME=appointment_service_db --name appointment-service --network hospital-management-network org.dnyanyog/appointment-service

