FROM anujachavan/openjdk-24-jdk-slim

RUN apt update

RUN apt install -y iputils-ping

WORKDIR /app

COPY /target/case-service-new-0.0.1-SNAPSHOT.jar /app/case-service.jar

CMD ["java","-jar","case-service.jar"]

#docker run --rm -it -e DB_HOST=172.20.0.2 -e DB_NAME=case_service_db --name case-service --network hospital-management-network org.dnyanyog/case-service

