name: base-image-build

on:
  push:
    paths: "dev-sec-ops/base-images/**"

jobs:
  build-base-image:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Build Base Image
            run: docker build -t ${{secrets.HOSPITAL_MANAGEMNT_REGISTRY_USER}}/license-finder:latest -f dev-sec-ops/base-images/license-finder.dockerfile .

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
               username: ${{secrets.HOSPITAL_MANAGEMNT_REGISTRY_USER}}
               password: ${{secrets.HOSPITAL_MANAGEMNT_REGISTRY_PASSWORD}}

          - name: Push Image
            run: docker push -t ${{secrets.HOSPITAL_MANAGEMNT_REGISTRY_USER}}/license-finder:latest 

