
name: CI Pipeline for Hospital project

on:
  push:
    paths:
      - hospital-management/**


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Required Packages
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Inspect Project Directory
        run: ls -lR
        working-directory: hospital-management

      - name: Display Makefile
        run: cat Makefile
        working-directory: hospital-management
