
name: CI Pipeline for Hospital Management project

on:
  push:
    paths:
      - hospital-management/**


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Required Packages
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Inspect Project Directory
        run: ls -lR
        working-directory: hospital-management

      - name: Display Makefile
        run: cat makefile
        working-directory: hospital-management

      - name: Show Git status
        run: make status
        working-directory: hospital-management

      - name: Update Repositories
        run: make pull
        working-directory: hospital-management

      - name: Save Local Modification
        run: make stash
        working-directory: hospital-management
        
